# Base blog settings
baseurl                      : "" # the subpath of your site,                         # e.g. /blog/
                              # set to '' in case of hosting on GitHub
url                          : "" # the base hostname & protocol for your site
                                  # `http://<username>.github.io` - for GitHub

blog:
  title                      : rlcj
  description                  : >
                               this should contain a proper description

# Layout configuration
  logo_path                  : "assets/images/logo.svg" # path to logo file
  search_path                : # "yourgitusername.github.io"
                               # needed for searchbox in archive page
  hero_layout                : true # turn on hero layout for blog and posts
  hero_placeholder           : "assets/images/generic_hero.jpg" # placeholder for hero image
  excerpts                   : true # show excerpts instead of full post content on blog page
  inline_footnotes           : true # enable/disable barefoot inline footnotes
  titles_only                : false # show post titles only on main blog page

# Fonts
  font                       : '"Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
  load_google_fonts          : 'Rubik:400,400italic,700,700italic'


# Author info
author:
  fullname                  : Your Name
  rss                       : true # generate RSS feed and show it's icon in header
  mail                      : your@email.com # change to your e-mail address
  twitter                   : twitter-user-name
  github                    : github-user-name
  youtube                   : youtube-user-name
  stackoverflow             : stackoverflow-user-name
  disqus                    : rlcj # your disqus site name
  google_analytics          : # 'UA-XXXXXXXX-X'
  photo                     : "assets/images/me2.png"
  photo2x                   : "assets/images/me.png"



## !!
## Advanced blog settings
## You should not change anything here unless you know what you are doing

# Gems
# plugins:

# Permalinks
permalink                    : posts/:slug

# Tags
collections:
  tags:
    output: true
    permalink: /tags/:slug/
  projects:
    output: true
    permalink: /projects/:slug/
defaults:
  -
    scope:
      path: ""
      type: tags
    values:
      layout: blog-by-tag
  -
    scope:
      path: ""
      type: projects
    values:
      layout: blog-by-project

# Handling Reading
exclude                    : ["README.md", "README.html"]


# Sass settings
sass:
  sass_dir                : _sass
  style                   : compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings               : all
  endings                 : all
  comments                : ["<!-- ", " -->"]
  blanklines              : true
  profile                 : false
  ignore:
  envs                    : [local]